### ISSUE TITLE
Bucket creation fails: unauthorized for application key

### ISSUE THREAD

**Issue by kontrollanten** [Backblaze/terraform-provider-b2#69]
Hi,

We're trying to migrate to Backblaze b2 and have added the following to our TF templates:

```
provider "b2" {
  application_key     = var.backblaze_application_key
  application_key_id  = var.backblaze_application_key_id
}

resource "b2_bucket" "stream_storage" {
  bucket_name = "${var.project_name}-${var.environment}-storage"
  bucket_type = "allPublic"
}
```

The Backblaze key:

```
keyID:
[secret]
keyName:
terraform-cloud
bucketName:
-
capabilities:
bypassGovernance, deleteBuckets, deleteFiles, deleteKeys, listBuckets, listFiles, listKeys, readBucketEncryption, readBucketReplications, readBucketRetentions, readBuckets, readFileLegalHolds, readFileRetentions, readFiles, shareFiles, writeBucketEncryption, writeBucketReplications, writeBucketRetentions, writeBuckets, writeFileLegalHolds, writeFileRetentions, writeFiles, writeKeys
expiration:
-
namePrefix:
(none)

```

Which results in the error below. We've tried using B2_APPLICATION_KEY/B2_APPLICATION_KEY_ID env variables as well, but it results in the same error.

```
2024-02-15T06:40:51.178Z [DEBUG] b2_bucket.stream_storage: applying the planned Create change
2024-02-15T06:40:51.179Z [INFO]  provider.terraform-provider-b2_0.8.9: 2024/02/15 06:40:51 [DEBUG] setting computed for "options" from ComputedKeys: timestamp=2024-02-15T06:40:51.179Z
2024-02-15T06:40:51.179Z [INFO]  provider.terraform-provider-b2_0.8.9: 2024/02/15 06:40:51 [TRACE] Executing pybindings for 'bucket' and 'resource_create' operation: timestamp=2024-02-15T06:40:51.179Z
2024-02-15T06:40:51.179Z [INFO]  provider.terraform-provider-b2_0.8.9: 2024/02/15 06:40:51 [TRACE] Input for pybindings: map[bucket_info:map[] bucket_name:swebbtv-test-peertube-storage bucket_type:allPublic cors_rules:[] default_server_side_encryption:[] file_lock_configuration:[] lifecycle_rules:[]]: timestamp=2024-02-15T06:40:51.179Z
2024-02-15T06:40:53.307Z [INFO]  provider.terraform-provider-b2_0.8.9: 2024/02/15 06:40:53 [ERROR] Error in pybindings: dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
Traceback (most recent call last):
File "b2sdk/session.py", line 466, in _reauthorization_loop
File "b2sdk/session.py", line 456, in _api_token_callback
File "b2sdk/raw_api.py", line 458, in create_bucket
File "b2sdk/raw_api.py", line 413, in _post_json
File "b2sdk/b2http.py", line 276, in post_json_return_json
File "b2sdk/b2http.py", line 235, in post_content_return_json
File "b2sdk/b2http.py", line 462, in _translate_and_retry
File "b2sdk/b2http.py", line 397, in _translate_errors
b2sdk.exception.Unauthorized:  (unauthorized)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "b2_terraform/provider_tool.py", line 527, in run_command
File "b2_terraform/provider_tool.py", line 131, in run
File "b2_terraform/provider_tool.py", line 231, in resource_create
File "logfury/_logfury/trace_call.py", line 86, in wrapper
File "b2sdk/api.py", line 242, in create_bucket
File "b2sdk/session.py", line 152, in create_bucket
File "b2sdk/session.py", line 445, in _wrap_default_token
File "b2sdk/session.py", line 451, in _wrap_token
File "b2sdk/session.py", line 475, in _reauthorization_loop
b2sdk.exception.Unauthorized: unauthorized for application key with capabilities 'shareFiles,readFileRetentions,writeKeys,readBucketEncryption,deleteBuckets,readFileLegalHolds,bypassGovernance,writeFileRetentions,listKeys,readBuckets,writeFiles,listFiles,deleteKeys,writeBucketEncryption,readBucketRetentions,writeFileLegalHolds,writeBucketReplications,readFiles,readBucketReplications,writeBucketRetentions,listBuckets,writeBuckets,deleteFiles' (unauthorized): timestamp=2024-02-15T06:40:53.307Z
2024-02-15T06:40:53.307Z [ERROR] provider.terraform-provider-b2_0.8.9: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/diag/diagnostics.go:62 tf_rpc=ApplyResourceChange @module=sdk.proto tf_req_id=fd1d3a65-4bdb-67cb-a8b1-6b50b8b392e3 tf_resource_type=b2_bucket diagnostic_severity=ERROR
diagnostic_summary=
| dateutil/zoneinfo/__init__.py:26: UserWarning: I/O error(2): No such file or directory
| Traceback (most recent call last):
|   File "b2sdk/session.py", line 466, in _reauthorization_loop
|   File "b2sdk/session.py", line 456, in _api_token_callback
|   File "b2sdk/raw_api.py", line 458, in create_bucket
|   File "b2sdk/raw_api.py", line 413, in _post_json
|   File "b2sdk/b2http.py", line 276, in post_json_return_json
|   File "b2sdk/b2http.py", line 235, in post_content_return_json
|   File "b2sdk/b2http.py", line 462, in _translate_and_retry
|   File "b2sdk/b2http.py", line 397, in _translate_errors
| b2sdk.exception.Unauthorized:  (unauthorized)
```

Environment: Terraform Cloud
Terraform version: 1.7.3

**Comment by kontrollanten** [comment]
It seemed that when creating a second public bucket it was required to pay $1 before getting further. By creating a bucket manually in the web interface (and paying $1) I was able to solve this.

Maybe not an issue for this project, but it would be great to have a more clear error message, I spent a lot of hours on this issue.

**Comment by ooola** [comment]
Thank you for reporting the issue. A ticket has been opened to look into the issue.

mvh!
