### ISSUE TITLE
Error: PotentialS3EndpointPassedAsRealm

### ISSUE THREAD

**Issue by ngladkikh** [Backblaze/terraform-provider-b2#79]
I’m encountering an error while creating a bucket using the B2 Terraform provider.

The `terraform plan` output:
```
Changes to Outputs:
  - bucket_id         = "nextcloud-data-test-ec1a7b38-028e-aaed-8ab1-8bf0f44badc6" -> null
  - bucket_key        = "003b010de8b10d6000000000a" -> null
  - bucket_secret     = (sensitive value) -> null
╷
│ Error: Traceback (most recent call last):
│   File "b2sdk/_internal/b2http.py", line 489, in _translate_errors
│   File "json/__init__.py", line 346, in loads
│   File "json/decoder.py", line 337, in decode
│   File "json/decoder.py", line 355, in raw_decode
│ json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
│ 
│ During handling of the above exception, another exception occurred:
│ 
│ Traceback (most recent call last):
│   File "b2_terraform/provider_tool.py", line 524, in run_command
│   File "b2_terraform/provider_tool.py", line 150, in run
│   File "b2_terraform/provider_tool.py", line 159, in provider_authorize_account
│   File "logfury/_logfury/trace_call.py", line 86, in wrapper
│   File "b2sdk/v2/api.py", line 54, in authorize_account
│   File "logfury/_logfury/trace_call.py", line 86, in wrapper
│   File "b2sdk/_internal/api.py", line 223, in authorize_account
│   File "b2sdk/_internal/session.py", line 116, in authorize_account
│   File "b2sdk/_internal/raw_api.py", line 555, in authorize_account
│   File "b2sdk/_internal/raw_api.py", line 546, in _post_json
│   File "b2sdk/_internal/b2http.py", line 390, in post_json_return_json
│   File "b2sdk/_internal/b2http.py", line 356, in post_content_return_json
│   File "b2sdk/_internal/b2http.py", line 309, in request_content_return_json
│   File "b2sdk/_internal/b2http.py", line 279, in request
│   File "b2sdk/_internal/b2http.py", line 588, in _translate_and_retry
│   File "b2sdk/v2/b2http.py", line 22, in _translate_errors
│   File "b2sdk/_internal/b2http.py", line 498, in _translate_errors
│ b2sdk._internal.exception.PotentialS3EndpointPassedAsRealm: Potential s3 endpoint passed as realm: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
│ <Error>
│     <Code>NotImplemented</Code>
│     <Message>This API call is not supported.</Message>
│ </Error>
│ 
│ 
│ 
│   with b2_bucket.nextcloud_bucket,
│   on b2_bucket.tf line 4, in resource "b2_bucket" "nextcloud_bucket":
│    4: resource "b2_bucket" "nextcloud_bucket" {
│ 
╵
```

The bucket terraform file:

```
provider "b2" {
  endpoint = "https://s3.eu-central-003.backblazeb2.com"
}

resource "random_uuid" "bucket_suffix" {
}

resource "b2_bucket" "nextcloud_bucket" {
  bucket_name = "nextcloud-data-test-${random_uuid.bucket_suffix.result}"
  bucket_type = "allPrivate"

  lifecycle_rules {
    days_from_hiding_to_deleting = 1
    file_name_prefix             = ""
  }
}

resource "b2_application_key" "nextcloud_app_key" {
  key_name     = "nextcloud-b2-key-${random_uuid.bucket_suffix.result}"
  bucket_id    = b2_bucket.nextcloud_bucket.bucket_id
  capabilities = ["listBuckets", "listFiles", "readFiles", "writeFiles", "deleteFiles"]
}
```

In case when I omit `endpoint` option the `terraform plan` output:

```
Changes to Outputs:
  - bucket_id         = "nextcloud-data-test-ec1a7b38-028e-aaed-8ab1-8bf0f44badc6" -> null
  - bucket_key        = "003b010de8b10d6000000000a" -> null
  - bucket_secret     = (sensitive value) -> null
╷
│ Error: Traceback (most recent call last):
│   File "b2sdk/_internal/b2http.py", line 485, in _translate_errors
│   File "b2sdk/_internal/b2http.py", line 267, in do_request
│   File "requests/sessions.py", line 575, in request
│   File "requests/sessions.py", line 484, in prepare_request
│   File "requests/models.py", line 367, in prepare
│   File "requests/models.py", line 438, in prepare_url
│ requests.exceptions.MissingSchema: Invalid URL 's3.eu-central-003.backblazeb2.com/b2api/v2/b2_authorize_account': No scheme supplied. Perhaps you meant https://s3.eu-central-003.backblazeb2.com/b2api/v2/b2_authorize_account?
│ 
│ During handling of the above exception, another exception occurred:
│ 
│ Traceback (most recent call last):
│   File "b2_terraform/provider_tool.py", line 524, in run_command
│   File "b2_terraform/provider_tool.py", line 150, in run
│   File "b2_terraform/provider_tool.py", line 159, in provider_authorize_account
│   File "logfury/_logfury/trace_call.py", line 86, in wrapper
│   File "b2sdk/v2/api.py", line 54, in authorize_account
│   File "logfury/_logfury/trace_call.py", line 86, in wrapper
│   File "b2sdk/_internal/api.py", line 223, in authorize_account
│   File "b2sdk/_internal/session.py", line 116, in authorize_account
│   File "b2sdk/_internal/raw_api.py", line 555, in authorize_account
│   File "b2sdk/_internal/raw_api.py", line 546, in _post_json
│   File "b2sdk/_internal/b2http.py", line 390, in post_json_return_json
│   File "b2sdk/_internal/b2http.py", line 356, in post_content_return_json
│   File "b2sdk/_internal/b2http.py", line 309, in request_content_return_json
│   File "b2sdk/_internal/b2http.py", line 279, in request
│   File "b2sdk/_internal/b2http.py", line 588, in _translate_and_retry
│   File "b2sdk/v2/b2http.py", line 22, in _translate_errors
│   File "b2sdk/_internal/b2http.py", line 569, in _translate_errors
│ b2sdk._internal.exception.UnknownError: Unknown error: MissingSchema("Invalid URL 's3.eu-central-003.backblazeb2.com/b2api/v2/b2_authorize_account': No scheme supplied. Perhaps you meant https://s3.eu-central-003.backblazeb2.com/b2api/v2/b2_authorize_account?")
│ 
│ 
│   with b2_bucket.nextcloud_bucket,
│   on b2_bucket.tf line 4, in resource "b2_bucket" "nextcloud_bucket":
│    4: resource "b2_bucket" "nextcloud_bucket" {
│ 
╵
```

**Comment by ngladkikh** [comment]
Provider details:
```
provider "registry.terraform.io/backblaze/b2" {
  version     = "0.8.12"
  constraints = "~> 0.2"
  hashes = [
    "h1:DKZehZTdHC0fJzAA74yMzUaHm1PisNaNaBQjAOSS9kk=",
    "zh:bc9d25d21adeafba8edde8d6ffb6150cd5c86c207412c8941347966be3363de5",
    "zh:c538eaea1b15379635b9d8a2cb862248813022bb0de5481741f18fcc77a10a1b",
    "zh:cc2767797ad27b9a3b4ad97b6a2f3eeea9f50a6000bbcfa9b44189945dae30b3",
    "zh:d83b5f0e632ea56570a0737c1896f049367201cc67f5de83baa24272ccdd56a4",
  ]
}
```

**Comment by mlech-reef** [comment]
@ngladkikh remove

```
endpoint = "https://s3.eu-central-003.backblazeb2.com"
```

This provider works with the native B2 API, not the S3-compatible API. B2 endpoint should be either `production` (this is the default value) or a custom URL (e.g. for testing) and in most of the cases should be left untouched.

Best regards,
Maceik

**Comment by ngladkikh** [comment]
I started without the endpoint parameter, and the error was:
```
b2sdk._internal.exception.PotentialS3EndpointPassedAsRealm: Potential s3 endpoint passed as realm: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
│ <Error>
│     <Code>NotImplemented</Code>
│     <Message>This API call is not supported.</Message>
│ </Error>
```
Where can I find the correct endpoint value @mlech-reef? The bucket details do not contain anything starting with `production.`

**Comment by metadaddy** [comment]
Hi @ngladkikh - that error means that, for some reason, the provider is attempting to use an S3 API endpoint, rather than the B2 Native API endpoint.

Aside from the `endpoint` configuration in the provider, the only other way I can think of that this might be happening is if you have set the `B2_ENDPOINT` environment variable. If so, you should unset it - the default value is `production`. Other values are used internally at Backblaze to point to our development and staging infrastructure, which you can't access anyway.

**Comment by ngladkikh** [comment]
The B2_ENDPOINT environment variable was set to `s3:...`, which is the root cause. Removing the B2_ENDPOINT environment variable solved the issue. This particular issue probably deserves to be explained in the documentation. Thank you for your help @metadaddy, @mlech-reef!
